ctti-clinicaltrials/aact

app/models/clinical_trials/file_manager.rb, app/models/mesh_heading.rb, db/migrate/20170411000122_create_mesh_thesaurus.rb, db/structure.sql, public/mesh_headings.txt
Headings provided by NLM: https://www.nlm.nih.gov/mesh/2017/download/2017NewHeadingsByCategorySingleColumn508.txt
=> aact-348: add table of MeSH Headings

app/models/category.rb, db/structure.sql, lib/tasks/load.rake
I also changed category update method to use 1000 days by default instead of…14 days, and to not take arguments when run with db:load
=> Fixed excel error for download

app/models/category.rb, app/models/util/rss_reader.rb, lib/tasks/load.rake
added hitting the api in batches and the time to the filename.
=> Loop in batches

app/models/category.rb
I made some edits to fix the error when opening the file in excel
=> Minor edits

app/documents/LeadingCausesDeath_terms.csv, app/models/category.rb, app/models/search.rb, app/models/util/db_manager.rb, app/models/util/updater.rb, db/migrate/20200922153536_add_grouping_to_categories.rb, db/migrate/20200922175002_add_index_to_categories.rb, db/migrate/20200922181240_create_searches.rb, db/structure.sql, lib/tasks/load.rake, spec/factories.rb, spec/models/search_spec.rb
Expanded categories to include other conditions beyond 'covid-19'. Set up system to search for studies matching saved queries (populated from a csv) and create new category connections as needed.
=> Editing categories

db/migrate/20200922175002_add_index_to_categories.rb, db/structure.sql
=> Category index fix

app/models/category.rb, app/models/search.rb, app/models/util/updater.rb, db/migrate/20200922175002_add_index_to_categories.rb, db/migrate/20201201210834_remove_last_modified_from_categories.rb, db/migrate/20201201235004_add_name_to_searches.rb, db/migrate/20201207173334_add_beta_api_to_searches.rb, db/structure.sql, lib/tasks/load.rake, spec/factories.rb
Moved search methods to the search model and added a method for creating a funder search
=> Funder type search

app/models/util/updater.rb
Needs to be merged to fix a bug with finalizing the load.
=> I fixed a bug with event_type

app/models/support/sanity_check.rb, app/models/util/updater.rb
This PR addresses an issue when the sanity checks prevent refreshing the public database.
A type of sanity check counts the number of rows per table. The code required the number of those sanity checks to be 46. This is the original number of tables which have an nct_id. When we added another another table the number of sanity checks was no longer 46 and would fail to do a refresh.
This was taken out in this PR because if there are less tables running the sanity check will throw an exception. This will prevent the refreshing from happening.
If the number of tables is larger than what we expected, the most likely scenario is that we added another table. Preventing a refresh from happening because we forgot to change the number is more problematic.
=> fix problem with sanity checks preventing a restore

Gemfile.lock, app/models/study_json_record.rb
added check for if a study is patient registry type to add that to the study_type attribute
=> Fixed study_type in beta

app/models/util/updater.rb, db/structure.sql
I made it so calculated values are made during incremental load as well the as full load. 
The CalculatedValues populate method calls the method that sets the downcase name. I didn't see a reason to prevent CalculatedValues from being made during an incremental load so I removed the if statement that was preventing them from being made if it wasn't a full load.
Made a docker image: aact/core:4.6.8
=> downcase_name_fix

app/models/util/db_manager.rb, config/database.yml, db/structure.sql, lib/tasks/load.rake
decouple creating the database and restoring from file, we use the same code to restore the db to production
=> refactor some of the code that imports the database

Gemfile, Gemfile.lock, config/initializers/airbrake.rb
Completed setup for airbrake for aact-core.
=> Added airbrake to aact-core

README.md, app/models/search_result.rb, app/models/study_json_record.rb, app/models/util/file_manager.rb, app/models/util/updater.rb, lib/tasks/counts.rake, lib/tasks/load.rake
- migrate ctgov_beta_group_code column to ctgov_group_code column
- Write out the current workflow deployment process
- create a migration that renames columns in tables from ctgov_beta_group_code to ctgov_group_code
- As a developer I want the setup commands to be more clearly specified
- Have the StudyJsonRecord.data_verification method write out the results from the comparison
=> Release 5.0.0

app/models/study_json_record.rb
Added messages to method data_verification in file study_json_record.rb:
1. print message before starting all_data_collection for ctgov_beta
2. print message before starting all_data_collection for ctgov
3. Show the number we are at when looping through beta_counts.
=> Added messages to data_verification to know what is happening

app/models/study_json_record.rb
- Ran test for each air brake request in console seems to be working fine no errors
=> Add Airbrake Notify

app/models/study_json_record.rb
- Fixed result_group_id not being assigned a value in related tables
=> fixed missing result_groups_id

app/models/file_record.rb, db/migrate/20220212033048_create_file_records.rb, db/structure.sql, spec/factories.rb, spec/models/file_record_spec.rb
=> feat/aact- 290 added model FileRecord

app/models/support/load_event.rb, app/models/util/updater.rb, app/models/verifier.rb, db/migrate/20220429175157_add_load_event_id_to_verifiers.rb, db/structure.sql
The screenshots below show the association of load events with verifiers:
=> AACT-316 Associate load events and verifiers

README.md
- Add a requirements section in the README with instructions on how to install:
- zip - different instructions for mac/windows/linux
- graphviz with a link to page
=> Added requirements to README

app/models/study_json_record.rb, app/models/util/file_manager.rb
=> Moved file download from file_manager to study_json_record

app/models/study_json_record.rb, app/models/util/db_manager.rb, db/migrate/20220919155542_add_participant_flow_to_milestones.rb, db/structure.sql
Add data to milestones, Fixed code in Util::DbManager so schema will load local
=> AACT-429-Add-data-to-drop_withdrawls

app/models/study_json_record.rb, db/migrate/20220930181441_add_data_to_baseline_measurements.rb, db/structure.sql
=> Add data to baseline_measurements

app/models/calculated_value.rb
This was not needed in the backend database since no users access it
=> remove read_only revoke

db/migrate/20230214200400_add_active_to_study_searches.rb, db/structure.sql
Generated migration to add active boolean column to StudySearch model.
=> AACT-468: Generate a migration to add the active column to the study search

app/models/background_job.rb, db/migrate/20230216205237_create_background_jobs.rb, db/structure.sql, spec/factories.rb, spec/models/background_job_spec.rb
Created model for BackgroundJob and RSpec test file. 
Ran migration.
=> AACT-473: Create a model for background jobs in aact-core

spec/models/support_study_xml_record_spec.rb
Deleted Spec model test file support_study_xml_record_spec.rb because we now use json instead of xml.
=> AACT-554: Remove test file

config/database.yml
Added staging into development in database.yml so you'll be able to run rails c without staging error.
=> fix/AACT-560 Add staging into database.yml

spec/models/support_load_event_spec.rb
=> AACT-545 make the support_load_event tests pass

app/models/data_collection.rb
Create the new data_collection method with empty method
=> feat/AACT-583 create the new data_collection method

.dockerignore, .github/workflows/build-and-test-not-master.yml, .gitignore, Dockerfile, README.md, app/models/util/db_manager.rb
This PR removes connections.yml and all its dependencies.
=> Kostik/remove dependency for connectionsyml/aact 555

app/models/country.rb, app/models/study_json_record/processor_v2.rb, spec/models/country_spec.rb, spec/support/json_data/NCT02278341.json
- Created `mapper` method in `Country` class
- Removed xml mapping
- Added `locations_array` method in processor_v2.rb file
- Added RSpec test cases in country_spec.rb file
- All Test Cases PASS:
=> AACT-618: Create countries_data mapper method for the v2 API

app/models/provided_document.rb, app/models/study_json_record/processor_v2.rb, spec/models/provided_document_spec.rb, spec/support/json_data/NCT03064438.json
- Created mapper method in ProvidedDocument class
- Removed xml mapping
- Added RSpec test case in provided_document_spec.rb file
- All Test Cases PASS:
=> AACT-630: Create provided_documents_data mapper method for the v2 API

app/models/document.rb, app/models/study_json_record/processor_v2.rb, spec/models/document_spec.rb, spec/support/json_data/document.json
- Created a mapping definition in the model Document
- Removed xml, create_all_from and collect_docs methods from Document
- Removed mapper method from the model ProcessorV2
- document_spec test file PASS:
=> AACT-656: ctgov api v2 documents mapping

app/models/country.rb, spec/models/country_spec.rb, spec/support/json_data/country.json
- Created a mapping definition in the model Country
- Removed old JSON mapper method
- Created RSpec JSON data and modified test file.
- country_spec test file PASS:
=> AACT-665: ctgov api v2 countries mapping

app/models/ipd_information_type.rb, app/models/study_json_record/processor_v2.rb, spec/models/ipd_information_type_spec.rb, spec/support/json_data/ipd_information_type.json
- Created a mapping definition in the model IpdInformationType
- Removed old JSON mapper method from the model ProcessorV2
- Removed old code for importing using xml
- ipd_information_type_spec test file PASS:
=> AACT-663: ctgov api v2 ipd information type mapping

app/models/link.rb, app/models/study_json_record/processor_v2.rb, spec/models/link_spec.rb, spec/support/json_data/link.json
- Created a mapping definition in the model Link
- Removed old JSON mapper method from the model ProcessorV2
- Removed old code for importing using xml
- link_spec test file PASS:
=> AACT-660: ctgov api v2 links mapping

app/models/pending_result.rb, spec/models/pending_result_spec.rb, spec/support/json_data/pending_result.json
- Created a mapping definition in the model PendingResult
- Removed old JSON mapper method
- Created RSpec JSON data and test file.
- pending_result_spec test file PASS:
=> AACT-662: ctgov api v2 pending_results mapping

app/models/study_json_record/processor_v2.rb, app/models/study_reference.rb, spec/models/study_reference_spec.rb, spec/support/json_data/study_reference.json
- Created a mapping definition in the model StudyReference
- Removed mapper method from the model ProcessorV2
- Removed xml mapping, attribs method
=> AACT-661 ctgov api v2 study_references mapping

spec/models/facility_spec.rb, spec/support/json_data/facility.json
This PR adds 2 tests for the facility mapper.
=> AACT-671/add-tests-facilities-version2

app/models/result_agreement.rb, db/migrate/20240324222521_change_column_type_in_result_agreements.rb, spec/models/result_agreement_spec.rb, spec/support/json_data/result_agreement.json
- Created a mapping definition in the model ResultAgreement
- Removed xml mapping, attribs method
=> AACT-676 ctgov api v2 results_agreements mapping

app/models/design_outcome.rb, spec/models/design_outcome_spec.rb, spec/support/json_data/design_outcome.json
Created a mapping definition in the model DesignOutcome
Removed xml mapping, attribs method
Created RSpec json data and test file.
=> AACT-669 ctgov api v2 design_outcomes mapping

app/models/outcome.rb, app/models/study_json_record/worker.rb, spec/models/outcome_spec.rb, spec/support/json_data/outcome.json
- Created a mapping definition in the model Outcome
- Removed xml mapping, attribs method
=> AACT-664 ctgov api v2 outcomes mapping

app/models/intervention.rb, app/models/intervention_other_name.rb, spec/models/intervention_other_name_spec.rb, spec/support/json_data/intervention_other_name.json
- Created a mapping definition in the model `Intervention`
- Removed old JSON mapper method and old code for importing using xml from model `InterventionOtherName`
- Created RSpec JSON data and test file.
- intervention_other_name_spec test file PASS:
=> AACT-678: ctgov api v2 intervention_other_names mapping

app/models/retraction.rb, app/models/study_reference.rb, spec/models/retraction_spec.rb, spec/models/study_reference_spec.rb, spec/support/json_data/study_reference.json
- Created a mapping for retractions
- Added rspec testing for retractions
- Put StudyReference back to before so child_mapping will work
=> AACT-681 ctgov api v2 retractions mapping

app/models/facility_contact.rb, spec/models/facility_contact_spec.rb, spec/support/json_data/facility_contact.json
- Removed code from facilility_contact model & added json rspec test
=> AACT-693 ctgov api v2 facility_contacts mapping

app/models/facility_investigator.rb, spec/models/facility_investigator_spec.rb, spec/support/json_data/facility_investigator.json
- Added the testing for facility_investigator rspec
- Remove unneeded code in the facility_investigator model
=> AACT-694 ctgov api v2 facility_investigators mapping

Gemfile, Gemfile.lock, app/models/reported_event_total.rb, spec/models/reported_event_total_spec.rb, spec/support/json_data/reported_event_total.json
- updated mapping logic for reported event totals model
- added json data (reported_event_total.json)
- updated model's rspec test file: `rspec spec/models/reported_event_total_spec.rb`
=> AACT-677: ctgov api v2 reported event totals

app/models/study_json_record/worker.rb, spec/models/study_spec.rb, spec/support/json_data/study_data_initialize.json, spec/support/json_data/study_data_interventional.json, spec/support/json_data/study_data_patient_registry.json, spec/support/json_data/study_data_phases.json
- Fix the worker to handle cases where inverse association is nil
- Redo rspec and fix/format json
=> AACT-692 ctgov api v2 studies mapping

spec/models/outcome_spec.rb, spec/support/json_data/outcome.json
=> AACT-664 ctgov api v2 outcomes mapping  take 2

app/models/drop_withdrawal.rb, app/models/study_json_record/worker.rb, spec/models/drop_withdrawal_spec.rb, spec/support/json_data/drop_withdrawl.json
- Fix the flatten function to handle cases where data is nil
- Remove old code for importing using XML from the model
- Add the mapping to DropWithdrawal
=> AACT-687-ctgov api v2 drop_withdrawals mapping

app/models/study_downloader.rb, app/models/study_json_record/worker.rb, app/models/support/load_event.rb, app/models/util/updater_v2.rb
- download the latest version of the current studies by batches before updating records in db
- refactor downloader
- improve readability outputs for updater and worker
=> Fix/AACT-707 - Update Run Main Loop

app/models/util/db_manager.rb, app/models/util/updater_v2.rb, config/database.yml
- make sure that main loop of the UpdaterV2 works with ctgov schema
- comment out database config related to admin db
- clean up
=> Update continuous study update functionality

app/models/study_downloader.rb, app/models/util/db_manager.rb, config/database.yml, spec/models/study_downloader_spec.rb
- updated comparison logic
- handle possible errors by returning empty array
- add tests for new method implementation
=> Fix Date Comparison by Study Downloader

app/models/calculated_value.rb, app/models/calculated_value_legacy.rb, app/models/design_outcome.rb, app/models/eligibility.rb, app/models/facility.rb, app/models/mesh_heading.rb, app/models/mesh_term.rb, app/models/reported_event.rb, app/models/study.rb, app/models/study_downloader.rb, app/models/study_json_record/worker.rb, app/models/support/load_event.rb, app/models/util/db_manager.rb, app/models/util/updater_v2.rb, db/migrate/20240629204041_add_indexes_to_calculated_values_and_outcomes.rb, db/migrate/20240629205840_analyze_and_vacuum_tables.rb, db/migrate/20240702011922_add_unique_index_to_calculated_values_nct_id.rb, spec/models/calculated_value_spec.rb
What's included in this PR:
- the execute flow of UpdaterV2 changed to only process recently downloaded records
- new implementation of calculated value model with only processing specific study records (not all the table)
- backing up original calculated value implemention
- improve logging process and readability of description message of the load_event
- add scopes for involved models for easier data 
- add indexes and uniqueness constrainst for involved models
=> Refactor Calculated Values

app/models/calculated_value.rb, app/models/mesh_heading.rb, app/models/mesh_term.rb, app/models/study_json_record.rb, app/models/study_json_record/worker.rb, app/models/util/updater_v2.rb, db/migrate/20240711213617_add_unique_index_to_mesh_headings.rb, lib/tasks/load.rake, public/mesh/mesh_headings.txt, spec/models/calculated_value_spec.rb, spec/models/provided_document_spec.rb, spec/models/utils/util_table_exporter_spec.rb, spec/rails_helper.rb
Included in this PR:
- move calculating values from updater to the worker's process method
- improve worker's readability
- add custom rake task to recalculate all values (ex. if the logic changed or new field added)
- minor calculated value model refactoring
- fix the tests to use current ctgov schema
Didn't touch StudyDownloader in this PR - was thinking to do it in the different one after we finalize this logic
=> Refactor Updater Logic

app/models/facility.rb, db/migrate/20240901191204_add_geo_point_to_facilities.rb, spec/models/facility_spec.rb, spec/support/json_data/facility.json
- update Facility model
- update test
=> Add GeoPoint fields to Facility

README.md
updated snapshot file paths to have consistent naming
=> edited readMe to include correct snapshot file paths
