ctti-clinicaltrials/aact

- Capfile
- Gemfile
- Gemfile.lock
- Rakefile
- config/deploy.rb
- config/deploy/development.rb
- config/deploy/production.rb
Disabled the rake db:migrations (by removing the db role) because our server name is ctti-aact but postgresql doesn’t allow hyphens in usernames, (db name is ctti).  This caused the deployment to fail.
> aact-457:  Get capistrano deployments working on Duke servers.

- app/models/util/updater.rb
- db/structure.sql
I merged in the `downcase_name` fix for the conditions table.
The issue was that the `CalculatedValues` populate method was only called during the full load. That method calls a method that sets the `downcase_name`. I didn't see a reason to prevent `downcase_name` being set and `CalculatedValues` being made during the incremental load so I removed the if statement that was preventing it.
Made a docker image for this: aact/core:4.6.8
> Aact 4.6.8

- config/initializers/airbrake.rb
- Line 15 had an extra bracket fixed the typo.
- Put in code to ignore development environment on line 46 in.
> Fixing airbrake development environment

- app/models/study_json_record.rb
- lib/tasks/db.rake
This PR allows User to run `rake db:rename_columns` which will analyses what tables in the **ctgov_beta schema** have the column `ctgov_beta_group_code` and renames that column to `ctgov_group_code`.
Found references in the code that use `ctgov_beta_group_code` and change them to `ctgov_group_code`.
> Rename columns in ctgov_beta (AACT 169 & 168)

- app/models/study_json_record.rb
- app/models/util/db_manager.rb
- made edits to the how the result_groups_id is found so that it won't throw errors
- added verifier to blacklist
> hot-fix/AACT-265-blacklist_verifier_and_bug_fix_result_groups

- app/mailers/notifier.rb
- app/models/verifier.rb
- app/views/layouts/mailer.html.erb
- app/views/notifier/report_diff.html.erb
- Added a view stating differences 
- Create an action in Notifier with a link to the csv differences.
> Send out an email report about differences between clinicaltrials.gov and aact

- app/models/study_json_record.rb
- db/migrate/20220202152642_add_extension_to_result_contacts.rb
- db/structure.sql
The extension column was added to the result_contacts table. 
Method `result_contact_data` was refactored so phone and extensions are separated.
See screenshots in the task-288
> Feat/aact 288 Add extension

- app/models/util/db_manager.rb
- config/application.rb
Removed AACT_STATIC_FILE_DIR references from other parts of the application. Deleted constant AACT_STATIC_FILE_DIR from application.rb and db_manager.rb files.
> AACT-364 Remove AACT_STATIC_FILE_DIR references

- config/application.rb
- config/deploy.rb
Deleted APPLICATION_HOST constant from application.rb and deploy.rb files.
> AACT-366 Remove APPLICATION_HOST from aact-core.

- config/application.rb
In file config/application.rb, I deleted RACK_TIMEOUT because the rails server is not used in aact-core.
> AACT-365 Remove RACK_TIMEOUT

- Gemfile
- Gemfile.lock
- app/models/util/updater.rb
- spec/models/utils/util_updater_spec.rb
- Added an exception rescue to the Util::Updater#execute method so that we can handle Load Events that fail.
- Simulated an exception on AACT core Util::Updater#execute and tested that the Load Event attribute `status:` was set to "error" and `problems:` was set to the exception message. 
- Both were verified in AACT admin Events index and show views.
- Added a models Util::Updater#execute Spec test case to verify the functionality of the exception rescue.
> AACT-418: Add a rescue to the Util::Updater#execute method

- app/models/util/db_image_generator.rb
- lib/tasks/db.rake
[Work for AACT-485](https://codethedream.atlassian.net/browse/AACT-485)
> AACT-485: Format the table names in the schema image in snake_case

- Gemfile
- Gemfile.lock
- db/structure.sql
- Bumped activerecord-import gem to 1.4.1
- Go into terminal
- Start rails console: `rails c`
- Run command `bin/rake db:load` 
- Wait for it to finish with no errors (see image for the reference):
> Bump activerecord-import to 1.4.1

- lib/tasks/aact.rake
- Created Background Jobs rake task to process jobs:
- Background Jobs index page shows that Job ID: 335 has a status of "pending" and is "Queued":
- After the rake task process_jobs is run, Job ID: 335 is processed and now has a status of "complete" and Results contains the "Download" url for the CSV file:
When a background job contains an error, such as an SQL syntax error in Job ID: 964, the queued job status is set to "error", and the user error message is displayed:
> AACT-489: Create a rake task for background jobs

- .github/workflows/build-and-test-not-master.yml
- app/models/background_job/db_query.rb
- spec/factories.rb
Fixed the following two FAILs when running the RSpec tests using the GitHub workflow file build-and-test-not-master.yml:
`rspec ./spec/models/background_job/db_query_spec.rb:9 # BackgroundJob::DbQuery#process should complete successfully when there is a valid SQL query`
`rspec ./spec/models/background_job/db_query_spec.rb:17 # BackgroundJob::DbQuery#process should update the status to "error" for the user when the SQL query is invalid`
Including these **2 BackgroundJob failures**, there is a total of **85 failures**:
I de-bugged the code by adding print statements to find what caused the errors:
I modified the GitHub workflow file to add a temporary directory and file to store the output csv when the BackgroundJob::DbQuery#process method is called:
The **two tests PASS**. Now, there is a …
> AACT-548: Make the BackgroundJob tests pass

- config/application.rb
- db/staging_structure.sql
- We got rid of the aact-alt database.
- Removed any mention of AACT_ALT environment variables from appplication.rb and then tested that everything still works:
**Loading studies**
**Restoring the database**
> AACT-106: Remove AACT_ALT variables from applicaton.rb

- Dockerfile
- Running as the root user in docker creates a security vulnerability.
- Updated the Dockerfile so that we specify a different user to run our code inside docker.
> AACT-156: Change user to non-root in docker

- app/models/study_json_record/processor_v2.rb
- spec/models/study_json_record/processor_v2_spec.rb
- Created ipd_information_types_data mapper method in the v2 processor
- Added RSpec test case for the ipd_information_types_data method
- Test Case PASS in processor_v2_spec.rb:
> AACT-622: Create ipd_information_types_data mapper method in the v2 processor

- app/models/study_json_record/processor_v2.rb
- spec/models/study_json_record/processor_v2_spec.rb
- spec/support/json_data/NCT02552212.json
- Created keywords_data mapper method in the v2 processor
- Added RSpec test case for the keywords_data method
- Test Case PASS in processor_v2_spec.rb:
**Note**
@micronix needs to incorporate updates pertaining to utility method convert_to_date to fix 4 test case FAILs:
> AACT-623: Created keywords_data mapper method in the v2 processor

- app/models/design_outcome.rb
- app/models/study_json_record/processor_v2.rb
- spec/models/design_outcome_spec.rb
- spec/support/json_data/NCT00763412.json
- spec/support/json_data/NCT00973089.json
- spec/support/json_data/NCT03064438.json
- spec/support/json_data/design_outcome_empty.json
- Removed design_outcomes_data method from ProcessorV2 class
- Created mapper method in DesignOutcome class
- Removed xml mapping and attribs method
- Added RSpec test cases in design_outcome_spec.rb file
- All Test Cases PASS:
> AACT-628: Create design_outcomes_data mapper method for the v2 API

- app/models/sponsor.rb
- app/models/study_json_record/processor_v2.rb
- spec/models/sponsor_spec.rb
- spec/support/json_data/NCT00763412.json
- Removed sponsors_data method from ProcessorV2 class
- Created mapper method in Sponsor class
- Removed xml mapping and attribs method
- Added RSpec test cases in sponsor_spec.rb file
- All Test Cases PASS:
> AACT-638: Create sponsors_data mapper method for the v2 API

- app/models/util/updater_v2.rb
This PR fixes slow queries issues running against public database by adding indexes to the backend database before its snapshot restored to the public database.
Tested by running "slow" query provided by the user in the local version of public db (limited number of studies):
**without** indexes:
**with** indexes:
> Fix - Add Indexes to Public Database
